tophat/monodeploy

- .circleci/config.yml
Adding circleCi support so that we can automatically build off of master. 
Also added eslint for linting support
> feat:Added CircleCi build support

- .circleci/config.yml
Slight circleCi config changes
> feat: add tag filter to other jobs

- package.json
- src/index.js
- yarn.lock
Not sure what greenkeeper was doing in #58 🤷‍♀
> chore: Update all dev dependencies

- .github/workflows/pull-request.yml
- jest.config.js
> chore: fix codecov in CI

- .github/workflows/pull-request.yml
This adds a build step to the Lint/Test CI flow to set builds up for success in the move to the monorepo structure.
> ci: add build

- packages/cli/src/cli.test.ts
- packages/cli/src/cli.ts
- packages/cli/src/readConfigFile.ts
Fixes a bug in the implementation of the boolean overrides. Technically not released yet.
> fix(cli): allow config file to override boolean flags

- README.md
- packages/cli/src/cli.test.ts
- packages/cli/src/readConfigFile.ts
Resolve config file relative to cwd.
- Closes #297, fixes config file resolution
> fix(cli): resolve config file relative to cwd, close #297

- packages/cli/package.json
- packages/cli/src/cli.test.ts
- packages/cli/src/cli.ts
- packages/cli/src/readConfigFile.ts
- packages/cli/src/types.ts
- packages/cli/src/validateConfigFile.ts
- yarn.lock
Add schema validation to catch errors in the config file.
> fix(cli): add config file schema validation

- __mocks__/@yarnpkg/plugin-npm.ts
- packages/versions/src/getLatestPackageTags.ts
> fix(versions): respect registryUrl when fetching tags, close #312

- packages/git/src/gitCommands.ts
https://stackoverflow.com/a/463027
> fix(git): use asymmetric diff for determining commits to process

- packages/node/src/index.ts
e.g. This PR refactors the X logic, applying Y's algorithm to improve Z by K percent.
- Closes #0, a short description of the linked issue.
> fix(node): write empty changeset if no packages updated

- __mocks__/@monodeploy/git.ts
- packages/cli/src/cli.test.ts
- packages/cli/src/cli.ts
- packages/cli/src/types.ts
- packages/cli/src/validateConfigFile.ts
- packages/node/src/monodeploy.test.ts
- packages/node/src/utils/mergeDefaultConfig.test.ts
- packages/node/src/utils/mergeDefaultConfig.ts
- packages/publish/src/index.ts
- packages/types/src/types.ts
- Closes #317, add a way to skip git tags
> feat(cli): add no-git-tag option to disable git tagging, close #317

- packages/changelog/src/changelog.ts
- packages/changelog/src/prependChangelogFile.test.ts
- packages/changelog/src/prependChangelogFile.ts
- packages/changelog/src/writeChangesetFile.ts
- packages/io/src/backupPackage.ts
- packages/node/src/index.ts
- packages/node/src/tests/main.test.ts
- packages/node/src/utils/getRegistryUrl.test.ts
- packages/node/src/utils/getRegistryUrl.ts
- packages/publish/src/commitPublishChanges.ts
- packages/publish/src/createReleaseGitTags.ts
- packages/publish/src/getWorkspacesToPublish.test.ts
- packages/publish/src/getWorkspacesToPublish.ts
- packages/publish/src/index.ts
- packages/versions/src/applyReleases.test.ts
- packages/versions/src/applyReleases.ts
- packages/versions/src/getExplicitVersionStrategies.test.ts
- packages/versions/src/getExplicitVersionStrategies.ts
- packages/versions/src/getImplicitVersionStrategies.test.ts
- packages/versions/src/getImplicitVersionStrategies.ts
- packages/versions/src/getLatestPackageTags.test.ts
- packages/versions/src/getLatestPackageTags.ts
> refactor: destructure instead of positional args

- packages/types/src/types.ts
> feat(types): add changeset ignore patterns

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
The `setup-node` action used was old, updated it to latest.
> ci: update setup node

- package.json
- yarn.lock
The postinstall script is just an ad.
> chore: disable core-js-pure build (ads)

- packages/node/src/index.ts
- packages/node/src/utils/getRegistryUrl.test.ts
- packages/node/src/utils/getRegistryUrl.ts
- packages/versions/src/getLatestPackageTags.test.ts
- packages/versions/src/getLatestPackageTags.ts
https://github.com/yarnpkg/berry/pull/3028
> fix: normalize registry url

- package.json
- packages/changelog/package.json
- packages/cli/package.json
- packages/dependencies/package.json
- packages/git/package.json
- packages/git/src/parseRepositoryProperty.test.ts
- packages/git/src/parseRepositoryProperty.ts
- packages/io/package.json
- packages/logging/package.json
- packages/node/package.json
- packages/plugin-github/package.json
- packages/publish/package.json
- packages/types/package.json
- packages/versions/package.json
See https://github.com/renovatebot/renovate/discussions/10545
> fix: use and support repository url with subdirectories

- packages/cli/src/cli.test.ts
- packages/cli/src/cli.ts
- yarn.lock
Do not use the yargs "default" of false. Instead, allow it to be undefined and coalesce it so we can determine correct precedence.
- #389
> fix: consider prerelease flag from config file

- packages/changelog/mocks/conventional-config-fn.mock.ts
- packages/changelog/src/changelog.ts
- packages/changelog/src/writeChangesetFile.test.ts
- packages/versions/mocks/conventional-config-fn.mock.ts
- packages/versions/src/versionStrategy.test.ts
- packages/versions/src/versionStrategy.ts
> fix: support conventional changelog config factory functions

- gatsby/src/pages-md/configuration.md
- packages/changelog/mocks/conventional-config-fn.mock.ts
- packages/changelog/src/changelog.ts
- packages/changelog/src/index.ts
- packages/changelog/src/resolveConventionalConfig.test.ts
- packages/changelog/src/resolveConventionalConfig.ts
- packages/cli/package.json
- packages/cli/src/cli.test.ts
- packages/cli/src/validateConfigFile.ts
- packages/types/src/types.ts
- packages/versions/package.json
- packages/versions/src/versionStrategy.ts
- yarn.lock
> feat: support custom configuration for conventional changelog config

- packages/versions/package.json
- yarn.lock
Not sure why constraints didn't catch this. Will look into it.
> fix: add missing changelog dependency

- e2e-tests/tests/full.test.ts
- packages/publish/package.json
- packages/publish/src/commitPublishChanges.ts
- testUtils/git.ts
- testUtils/setupMonorepo.ts
- yarn.lock
closes https://github.com/tophat/monodeploy/pull/445
> fix: only commit pnp files if they exist

- packages/changelog/package.json
- packages/versions/src/versionStrategy.test.ts
- packages/versions/src/versionStrategy.ts
- yarn.lock
This is for the built-in conventional config.
> fix: inconsistent behaviour in experimental conventional config

- packages/io/src/backupPackage.ts
- packages/io/src/patchPackageJsons.ts
- packages/node/src/index.ts
- packages/node/src/tests/main.test.ts
feat: add progress bars for patching manifest and savepoints
> fix: fail on corrupt manifest patching

- gatsby/src/pages/configuration.mdx
- gatsby/src/pages/getting-started.mdx
- jest.config.js
- package.json
- packages/cli/package.json
- packages/cli/src/cli.test.ts
- packages/cli/src/command.ts
- packages/cli/src/presets/recommended.ts
- packages/cli/src/readConfigFile.ts
- packages/cli/src/validateConfigFile.ts
- yarn.lock
feat: monodeploy will auto-detect your monodeploy.config.js file
> feat: support for config presets

- packages/node/src/tests/groups.test.ts
- packages/versions/src/applyVersionStrategies.test.ts
- packages/versions/src/applyVersionStrategies.ts
- packages/versions/src/mergeVersionStrategies.ts
> fix: apply version strategy to largest version among group

- packages/versions/src/applyReleases.test.ts
- packages/versions/src/applyReleases.ts
- yarn.lock
> fix: handle prerelease updates off of non-prerelease base

- gatsby/src/pages/plugins.mdx
- packages/cli/package.json
- packages/cli/src/validateConfigFile.ts
- packages/node/src/index.ts
- packages/node/src/tests/plugins.test.ts
- packages/types/src/types.ts
- yarn.lock
Ability to pass options to plugins.
> feat: add support for plugin options

- packages/publish/src/getPublishConfig.ts
Bug introduced in 3.1.0 (never published)
> fix: bug where publish registry url was being ignored

- packages/node/src/tests/issues/issue-516.test.ts
- packages/versions/src/getExplicitVersionStrategies.ts
- testUtils/setupMonorepo.ts
Close https://github.com/tophat/monodeploy/issues/516
> fix: allow missing name on top-level private workspace

- .yarn/sdks/eslint/package.json
- .yarn/sdks/prettier/package.json
- .yarn/sdks/typescript/package.json
- e2e-tests/package.json
- package.json
- packages/changelog/package.json
- packages/cli/package.json
- packages/dependencies/package.json
- packages/git/package.json
- packages/io/package.json
- packages/logging/package.json
- packages/node/package.json
- packages/plugin-github/package.json
- packages/publish/package.json
- packages/types/package.json
- packages/versions/package.json
- testUtils/setupMonorepo.ts
- yarn.lock
> feat: target Yarn@3.6.0
