tophat/monodeploy

package.json, yarn.lock
Hard coding this lerna version to the one we are using internally so we can get full test coverage with the existing behaviour, since some of the stuff we are doing currently depends on the specific version of lerna. Once we have full test coverage at this specific version, we can have more confidence when upgrading lerna.
=> build: Fix lerna version for now

src/update-package-versions.js, test/__snapshots__/deployPackages.test.js.snap, test/deployPackages.test.js, test/setup.js
These tests still hard code the `@thm` scope, but we basically want to make sure we preserve functionality as we rip out this Top Hat-specific logic, so the first step is writing tests.
=> test: Add more tests for updating of package.json files

.dependabot/config.yml
We're depending on specific command outputs, so until we change that it's best to lock the version
=> chore: Ignore lerna updates

.editorconfig, README.md, src/cli.ts, src/core/prependChangelogFile.ts, src/core/publishPackages.ts, src/monodeploy.test.ts, src/monodeploy.ts, src/types.ts
Adds prepend changelog support as well as "--no-push" flag.
- Closes #209, prepend changelog support
There's a question as to whether the updated changelog should be auto-committed and pushed.
=> feat: add prepend changelog support, close #209

.yarn/sdks/eslint/package.json, README.md, src/cli.ts, src/core/getExplicitVersionStrategies.ts, src/core/publishPackages.ts, src/logging.ts, src/monodeploy.test.ts, src/monodeploy.ts, src/types.ts, src/utils/__mocks__/git.ts, src/utils/getCommitMessages.ts, src/utils/git.ts, src/utils/mergeDefaultConfig.ts, src/utils/pushTags.ts, src/utils/versionStrategy.ts
- Read commit sha when reading commit messages
- Applies version strategy per commit.
- Move option defaults after CLI, so we can re-use them with the API.
- Address CR by replacing leftPad with padStart.
- Closes #213 
=> feat: support multiple unconnected package publishing

.github/workflows/pull-request.yml, .github/workflows/release.yml, CONTRIBUTING.md, package.json
Moves build stage to prepack lifecycle hook to support installing from git source.
- Closes #217, support installing from git
=> chore: move build to prepack lifecycle hook

packages/changelog/src/prependChangelogFile.test.ts, packages/git/src/index.test.ts, packages/versions/src/getExplicitVersionStrategies.test.ts, testUtils/fs.ts, testUtils/git.ts, testUtils/index.ts, testUtils/misc.ts
This adds some coverage for `monodeploy-changelog`. Writing coverage for `writeChangesetFile` is a bit trickier due to the call to `require.resolve` that is in the path of using the conventional changelog config. As such, it'll be worked off in another PR.
=> test: add coverage for monodeploy-changelog

packages/publish/src/getWorkspacesToPublish.test.ts
Adds some coverage for `monodeploy-publish`
=> test: cov getWorkspacesToPublish

README.md
This swaps our the discontinued Slack workpsace badge for a new one that's linked to the Discord server.
=> chore: discontinue slack badge, add discord

packages/versions/src/applyReleases.test.ts, packages/versions/src/applyReleases.ts
Fixes a bug where we weren't updating dependency versions if there was no intended update.
=> fix(publish): default to registry tags, if no intended update

.eslintrc.js, README.md, packages/cli/package.json, packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/readConfigFile.ts, packages/cli/src/types.ts, yarn.lock
Introduces a `--config-file` flag to load config from a file.
- Closes #281, add configuration file support.
=> feat(cli): add configuration file support, close #281

README.md, packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/types.ts, packages/node/src/index.ts, packages/node/src/monodeploy.test.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/publish/src/index.ts, packages/types/src/types.ts, packages/versions/src/getLatestPackageTags.ts
Adds config option to disable use of a registry.
- Closes #293, add option to disable registry access
=> feat: add config option to skip registry reads and writes, close #293

packages/changelog/README.md, packages/cli/README.md, packages/dependencies/README.md, packages/git/README.md, packages/io/README.md, packages/io/src/patchPackageJsons.ts, packages/logging/README.md, packages/node/README.md, packages/publish/README.md, packages/types/README.md, packages/versions/README.md
We need to reload the workspaces after modifying them so the `workspace.manifest.raw` value is up to date. Otherwise, when we publish to npm, we publish an _old_ version of the package.json.
=> fix(publish): upload to npm the most recent package manifest

packages/git/src/gitCommands.ts, packages/git/src/index.test.ts
Otherwise "HEAD...HEAD" produces an empty diff.
=> fix(git): default to HEAD^ if no tag exists on initial publish

README.md, package.json, packages/changelog/src/writeChangesetFile.ts, packages/node/src/index.ts, packages/node/src/monodeploy.test.ts
Adds `--changeset-filename=-` support, which disables logging and just prints the changeset data.
=> feat(node): add plumbing mode for changeset data

package.json, packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/types.ts, packages/cli/src/validateConfigFile.ts, packages/node/src/monodeploy.test.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/publish/src/index.ts, packages/types/src/types.ts, packages/versions/package.json, packages/versions/src/getLatestPackageTags.ts, packages/versions/src/versionStrategy.ts, yarn.lock
We use JFrog internally and we were maxing out the connection pool by publishing ~100 simultaneous requests to the registry.
Lerna only publishes 1 at a time.
=> feat(cli): add network concurrency options to limit concurrent publishes

packages/changelog/src/changelog.ts
The conventional changelog writer already calls writerOpts.transform. No need to call it twice.
=> fix(changelog): do not transform commits twice

README.md, packages/changelog/package.json, packages/changelog/src/prependChangelogFile.test.ts, packages/changelog/src/prependChangelogFile.ts, packages/node/src/index.ts, yarn.lock
Adds a `<packageDir>` token which can be used in the changelog filename to creates changelogs per package.
- Closes #285 
=> feat(changelog): add per package changelog support

.github/workflows/pull-request.yml, lint-staged.config.js
This is useless right now since we run the tests using typescript. We'd have to build and switch to the built version to properly test against multiple node versions.
=> chore: run tests against multiple node versions, close #314

packages/git/src/gitCommands.ts
If using autoCommit with git.push, the push was running dry run mode.
=> fix: package.json and changelog modifications were not being pushed

README.md, packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/types.ts, packages/cli/src/validateConfigFile.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/versions/package.json, packages/versions/src/getExplicitVersionStrategies.test.ts, packages/versions/src/getExplicitVersionStrategies.ts, yarn.lock
Using the changesetIgnorePatterns config option, it is now possible to exclude files (via glob) from consideration when determining packages to apply version bump strategies to.
- Closes #346
=> feat: add changeset ignore patterns support, close #346

e2e-tests/package.json, e2e-tests/tests/full.test.ts, package.json, packages/changelog/src/changelog.ts, packages/node/src/tests/main.test.ts, packages/plugin-github/src/index.ts, yarn.lock
Stop generating changelogs dependents as they make it hard to find the "real" changes in changelogs and GitHub releases. We still publish the tag, so it shows up on the GitHub releases page, but no longer in some h1 header.
- Closes #355
=> fix: do not generate changelog for dependent packages

.github/workflows/pull-request.yml, .github/workflows/release.yml, jest.config.js, package.json, packages/io/src/patchPackageJsons.test.ts, packages/io/src/patchPackageJsons.ts, packages/versions/src/applyReleases.test.ts, yarn.lock
devDependencies do not need to be updated as they are not used externally, and therefore have no impact on the public API and behaviour
=> fix: do not update devDependencies when patching package.jsons

packages/plugin-github/package.json, yarn.lock
Without this change, I receive:
```
TypeError: Cannot read property 'length' of undefined
at computeLineStarts (/Users/noah/repos/monodeploy/.yarn/unplugged/typescript-patch-f44dec8005/node_modules/typescript/lib/typescript.js:9585:27)
at Object.getLineStarts (/Users/noah/repos/monodeploy/.yarn/unplugged/typescript-patch-f44dec8005/node_modules/typescript/lib/typescript.js:9645:60)
at getCurrentLineMap (/Users/noah/repos/monodeploy/.yarn/unplugged/typescript-patch-f44dec8005/node_modules/typescript/lib/typescript.js:101624:59)
at emitDetachedCommentsAndUpdateCommentsInfo (/Users/noah/repos/monodeploy/.yarn/unplugged/typescript-patch-f44dec8005/node_modules/typescript/lib/typescript.js:105335:94)
at emitBodyWithDetachedComments (/Users/noah/repos/monodeploy/.yarn/unplugged/typescript-patch- …
```
=> fix: plugin-github should declare monodeploy dependencies

packages/changelog/src/writeChangesetFile.ts, packages/io/src/patchPackageJsons.ts, packages/node/src/index.ts, packages/node/src/utils/convert.ts, packages/publish/src/createReleaseGitTags.ts, packages/types/src/types.ts, packages/versions/src/applyReleases.test.ts, packages/versions/src/applyReleases.ts, packages/versions/src/getLatestPackageTags.test.ts, packages/versions/src/getLatestPackageTags.ts
Refactors internal APIs to support accessing non-latest npm dist tags.
This is a refactor in advance of pre-release support.
=> fix: refactor APIs to support non-latest dist tag

packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/types.ts, packages/cli/src/validateConfigFile.ts, packages/node/src/tests/dryRun.test.ts, packages/node/src/tests/lifecycleScripts.test.ts, packages/node/src/tests/main.test.ts, packages/node/src/tests/plugins.test.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/types/src/types.ts, packages/versions/src/versionStrategy.test.ts
Adds `prerelease` and `prereleaseId` config options. This does not add the actual prerelease implementation, just the options.
=> feat: add prerelease config options

__mocks__/@monodeploy/git.ts, e2e-tests/helpers/setupProject.ts, packages/git/src/gitCommands.ts, packages/git/src/index.mocked.test.ts, packages/git/src/index.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, testUtils/git.ts
Makes `@monodeploy/git` aware of pre-release mode. Mainly, to exclude prerelease tags in determining the base commit outside of pre-release mode.
- Closes #351, as I was refactoring the git commands anyway.
=> feat(git): support pre-release mode

packages/cli/src/cli.ts
I have noticed that the `prerelease: true` in my `monodeploy.config.js` is getting ignored. This was caused due to the fact that `argv.prerelease` has a default value `false`.
This is small change to support reading `prerelease` from the config file. It's handled in the same way as `autoCommit` flag.
=> fix: consider `prerelease` flag from config file

packages/io/src/executeLifecycleScript.ts, packages/io/src/patchPackageJsons.test.ts, packages/io/src/patchPackageJsons.ts, packages/node/src/index.ts, packages/node/src/tests/lifecycleScripts.test.ts, packages/publish/src/index.ts, packages/publish/src/prepare.ts
Do not modify filesystem in dry run mode. Since lifecycle scripts can have arbitrary side-effects, we'll also disable them in dry run.
- Closes #390
=> fix: do not modify any files in dry run mode

gatsby/src/pages-md/configuration.md, packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/types.ts, packages/cli/src/validateConfigFile.ts, packages/node/src/tests/main.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/publish/src/index.ts, packages/types/src/types.ts
https://github.com/tophat/monodeploy/issues/406
=> fix: add 'infer' access option to provide backwards compatibility

packages/cli/src/cli.test.ts, packages/cli/src/cli.ts, packages/cli/src/types.ts, packages/cli/src/validateConfigFile.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/types/src/types.ts, packages/versions/src/getExplicitVersionStrategies.test.ts, packages/versions/src/getExplicitVersionStrategies.ts
This adds support for an array of regular expressions which can be used to filter out commits from the explicit package bump detection. The patterns are matched against commits of the form <sha><newline><body> in multiline mode.
Related to #402
=> feat: add commit ignore patterns config option

e2e-tests/tests/full.test.ts, packages/node/src/index.ts
Re-run a yarn install after updating the manifests and publishing in order to ensure the most up to date yarn.lock is committed back to the repository. This is only necessary when persisting versions.
- Closes #416, by offering an alternative to the root problem of failing immutable installs
=> fix: re-install project when persisting versions

e2e-tests/tests/full.test.ts, packages/cli/package.json, packages/node/CHANGELOG.md, packages/node/package.json, packages/node/src/index.ts, yarn.lock
Revert #417
It's not respecting the workspace protocol because of the "in-memory" modifications in the patching step.
=> chore: revert 417

e2e-tests/tests/full.test.ts, packages/node/src/index.ts
This PR fixes an issue where after running monodeploy with persistVersions enabled, running `yarn` would produce a modified yarn.lock. This causes "yarn immutable" CI checks to fail. This PR re-installs the project after publishing to ensure the yarn.lock is up-to-date.
- Closes #416
=> fix: re-install project when persisting versions (#417)

packages/versions/src/getExplicitVersionStrategies.ts
=> fix: use a portable path when determining modified files

packages/changelog/src/changelog.ts, packages/node/src/tests/main.test.ts
Uses side notes from https://github.com/conventional-changelog/conventional-changelog/tree/d7477814399c8687ba705d03dea28f8648c0c855/packages/conventional-commits-parser#other-parts
=> fix: bug where only the latest sha was being written in the changelog

packages/dependencies/src/getTopologicalSort.test.ts, packages/dependencies/src/getTopologicalSort.ts
`tryWorkspaceByDescriptor` internally uses `tryWorkspaceByIdent` but in addition to that it checks if the workspace version matches the descriptor version range when using workspace protocol. This resulted in topological order of workspaces calculated incorrectly. See #422 for more context.
This fixes #422 
=> fix: use `tryWorkspaceByIdent` instead of `tryWorkspaceByDescriptor`

codecov.yml, packages/git/src/index.test.ts
This prevents the introduction of this reverted commit: https://github.com/tophat/monodeploy/pull/425
=> test: coverage for merge commits in commit detection

packages/node/src/tests/main.test.ts, packages/publish/src/commitPublishChanges.ts
In some environments (Github Actions) bash doesn't handle `**` globs well thus `git add yarn.lock package.json "**/package.json" **/CHANGELOG.md` doesn't stage `CHANGELOG.md` files if they're nested 2 folders deep:
To fix this we need to wrap the glob in quotes, so that globbing is performed by Git, not shell.
=> fix: wrap changelog filename in quotes to perform globbing by git

packages/dependencies/src/getTopologicalSort.test.ts, packages/dependencies/src/getTopologicalSort.ts, testUtils/setupMonorepo.ts
Assuming there's a cycle because we've visited a workspace beyond a certain count is an inefficient and incorrect way of determining a cycle. Instead, we look at the max "level" detected. Since all workspaces start at level 0, and increase by when during children detection (and propagation of the levels), the levels should never exceed the max number of edges in a path within a directed DAG. The maximum path size in a directed DAG is the number of nodes - 1. Exceeding this implies a directed edge to a node already part of the path, which is a cycle.
- Closes #442, and included the example from #442 as a test.
=> fix: overeager detection of cycles in topological sort

gatsby/src/pages/getting-started.mdx, packages/node/src/tests/main.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/types/src/types.ts, yarn.lock
BREAKING CHANGE: Change the default of the 'access' config option from public to infer. This reduces risk of accidental publish of private packages. The infer option respects the user's yarnrc.yml config, as well as publishConfig.access manifest field.
Related: https://github.com/tophat/monodeploy/issues/406
=> fix: change access config option default from public to infer

packages/changelog/src/writeChangesetFile.test.ts, packages/changelog/src/writeChangesetFile.ts, packages/node/src/index.ts, packages/publish/src/commitPublishChanges.ts, packages/publish/src/createReleaseGitTags.ts, packages/publish/src/determineGitTags.ts, packages/publish/src/index.ts
BREAKING CHANGE: Monodeploy no longer tags the commit containing the code changes, but rather tags the later commit which contains the package.json changes and other publish artifacts. This is more inline with how Lerna operates and means the tag will match the version in the package.json, as well as the changelog files. If there is interest in adding back the old behaviour behind a configuration option, please open a GitHub issue.
We still need to update the gatsby documentation to reflect the pipeline change.
=> feat: tag the same commit which includes publish artifacts, #402

packages/node/src/index.ts, packages/types/src/types.ts, packages/versions/src/getLatestPackageTags.test.ts, packages/versions/src/getLatestPackageTags.ts, packages/versions/src/getRegistryUrl.test.ts, packages/versions/src/getRegistryUrl.ts
https://github.com/yarnpkg/berry/blob/c57f788778df611310f0e242ee9f805f84623139/packages/plugin-npm/sources/npmConfigUtils.ts#L37
=> fix: use per-scope fetch registry from .yarnrc.yml, #457

__mocks__/@monodeploy/git.ts, packages/git/src/getCommitMessages.ts, packages/git/src/gitCommands.ts, packages/git/src/index.mocked.test.ts, packages/git/src/index.test.ts, packages/node/src/index.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/types/src/types.ts
If no baseBranch is supplied, monodeploy defaults to the last tagged commit. If the last tagged commit is the HEAD commit, monodeploy should not perform any actions as everything is already up-to-date.
=> fix: perform no-op if base branch is tagged

gatsby/src/pages/faq.mdx, gatsby/src/pages/getting-started.mdx, packages/dependencies/src/getDependents.test.ts, packages/dependencies/src/getDependents.ts, packages/node/src/tests/groups.test.ts, packages/versions/src/applyReleases.ts, packages/versions/src/getExplicitVersionStrategies.ts, packages/versions/src/mergeVersionStrategies.ts
BREAKING CHANGE: Private workspaces are now no longer pruned prior to dependency graph traversal and when considering version strategies for a group. This means you can create a private workspace as a devDependency of other packages and updates to that private workspace will propagate to the dependents with the correct version strategy -- assuming all these packages are in the same group. The private package, although considered when determining the version strategy, is not published.
https://github.com/tophat/monodeploy/issues/467
=> feat: consider private workspaces when determining updates

packages/versions/src/applyVersionStrategies.test.ts, packages/versions/src/applyVersionStrategies.ts
closes https://github.com/tophat/monodeploy/issues/478
=> fix: populate pre-release from the manifest in noRegistry mode

.yarnrc.yml
Can't enable ESM loader until https://github.com/nodejs/node/pull/42840 is merged. Otherwise the Node 14 test hangs.
=> refactor: disable pnp esm loader

__mocks__/@yarnpkg/plugin-npm.ts, packages/versions/src/getLatestPackageTags.test.ts, packages/versions/src/getLatestPackageTags.ts
https://github.com/tophat/monodeploy/pull/499
closes #498
=> fix: TypeError when registry returns version as array

gatsby/src/pages/getting-started.mdx
Fixes the links in the getting started section that lead to a 404
e.g. This PR refactors the X logic, applying Y's algorithm to improve Z by K percent.
- Closes #518 
=> Fix links in getting started section

__mocks__/@monodeploy/git.ts, packages/git/src/gitCommands.ts, packages/node/src/index.ts, packages/publish/src/commitPublishChanges.ts
Alternative to https://github.com/tophat/monodeploy/pull/524, addressing https://github.com/tophat/monodeploy/issues/523.
This only addresses "verify git credentials" in non-dry run mode which is better than the current state of things.
=> feat: verify git commands before publishing packages

packages/node/src/tests/main.test.ts, packages/publish/src/commitPublishChanges.ts, packages/types/src/types.ts
If autocommit is enabled, monodeploy **always** follows the logic of `persistVersions` even if `persistVersions` is set to false. This change allows you commit changelogs without `persistVersions` being true.
- Closes #592, which introduced this problem
- Closes #591, which is the documentation for these features
=> fix: allow auto-committing without persisting versions

packages/git/src/gitCommands.ts, packages/publish/src/commitPublishChanges.ts
When we introduced this change https://github.com/tophat/monodeploy/pull/593 it ended up introducing a new failure case.
> 11:10:31  ➤ YN0001: │ Error: Executing 'git pull --rebase --no-verify origin' failed with code: 128
> 11:10:31  
> 11:10:31  error: cannot pull with rebase: You have unstaged changes.
> 11:10:31  error: please commit or stash them.
If you are committing changelogs but not persisting changes, then you cannot do a git pull with rebase, since the modified `package.json` files locally are still on the working branch. We need those files later on when publishing, so we cannot just clean/reset ([as was the strategy here](https://github.com/tophat/monodeploy/pull/594)). This adds an `--autostash` argument to the pull which will resolve the problem.
=> fix: Stash changes before pull

__mocks__/@monodeploy/git.ts, e2e-tests/tests/issues/issue-601.test.ts, packages/changelog/src/prependChangelogFile.ts, packages/git/src/gitCommands.ts, packages/node/src/index.ts, packages/publish/src/commitPublishChanges.ts
Addresses the changelog portion of #601. We move the changelog updates closer to the commit stage, and ensure we "refresh" the changelogs prior to prepending entries. This reduces the possibility of conflicts, assuming the pipeline running monodeploy takes appropriate measures to "lock" the publish stage (to limit concurrency). If a conflict is detected, we attempt a merge, preferring our changes over the remote.
=> fix: ensures changelog files are up to date before adding entries

.eslintignore, e2e-tests/tests/issues/issue-601.test.ts, packages/publish/src/commitPublishChanges.ts
Non-persist mode (persistVersions: false) is typically used for high throughput automated publish pipelines. In this case, it's better to attach the git tag to the last commit that is being published rather than the changelog commit, since the changelog commit can come _after_ newer changes and thus result in dropping valuable commits.
=> fix: attach git sha to initial commit for non-persist mode

package.json, packages/cli/src/types.ts, packages/cli/src/validateConfigFile.ts, packages/io/package.json, packages/io/src/patchPackageJsons.test.ts, packages/io/src/patchPackageJsons.ts, packages/node/src/utils/mergeDefaultConfig.test.ts, packages/node/src/utils/mergeDefaultConfig.ts, packages/types/src/types.ts, yarn.lock
NOTE: Set versionStrategy.coerceImplicitPeerDependency to patch/minor/major to round down the patched peerDependency version prior to publishing. Previously, if Pkg-A declared a peer on Pkg-B, the peerDependency version range would be kept up to date with the latest version of Pkg-B. This may be undesirable as it can produce unnecessary peer dependency incompatibility warnings when the public API of Pkg-B did not change from patch to patch.
=> feat: add versionStrategy config

packages/git/src/parseRepositoryProperty.test.ts, packages/git/src/parseRepositoryProperty.ts
Fixes the `parseRepositoryProperty` function to correctly parse repository urls if there are multiple subgroups in it.
Relates to #782 
=> fix: parse repository subgroup correctly

gatsby/src/pages/plugins.mdx
The Plugins page has incorrect information on passing options to plugins. This PR fixes that.
While I was developing a plugin with custom options, I noticed that monodeploy would throw when I specified the options the way it is described in the docs. So I updated the docs to reflect the actual behavior.
=> docs: clarify plugin options usage

gatsby/src/pages/getting-started.mdx
This PR adds a section at the top of the Getting Started guide clarifying the minimum version of git supported
- Closes #411
My default formatter for mdx files as run through VSCode's defaults made several changes unrelated to the small contribution here. This led me to dig in and discover there are options for linting mdx files for consistency if this project/org is interested in enabling them.
=> docs: add detailed system requirements incl. git

.yarn/sdks/eslint/bin/eslint.js, .yarn/sdks/prettier/bin/prettier.cjs, .yarn/sdks/prettier/index.cjs, .yarn/sdks/typescript/bin/tsc, .yarn/sdks/typescript/bin/tsserver, .yarnrc.yml, e2e-tests/package.json, package.json, packages/changelog/package.json, packages/cli/package.json, packages/dependencies/package.json, packages/git/package.json, packages/io/package.json, packages/logging/package.json, packages/node/package.json, packages/plugin-github/package.json, packages/publish/package.json, packages/types/package.json, packages/versions/package.json, yarn.lock
This PR updates yarn to the latest version to fix an issue where the yarn.lock changes each time the changelog is updated. This happens because of some checksum changes in an earlier version of yarn.
- Closes #0, a short description of the linked issue.
=> deps: update yarn to 4.3.1
